export const repoUrls = [
	"https://github.com/utfunderscore/matchmaker-rs",
	"https://github.com/utfunderscore/ui-toolkit",
	"https://github.com/utfunderscore/hermes",
	"https://github.com/utfunderscore/loadbalancer-rs",
	"https://github.com/utfunderscore/game",
];

export const languageColors: Record<string, string> = {
	rust: "#dea584",
	kotlin: "#a97bff",
	java: "#b07219",
	javascript: "#f1e05a",
	typescript: "#3178c6",
	python: "#3572a5",
	go: "#00add8",
	ruby: "#701516",
	swift: "#ffac45",
	php: "#4f5d95",
	"c++": "#f34b7d",
	"c#": "#178600",
	c: "#555555",
	shell: "#89e051",
	html: "#e34c26",
	css: "#563d7c",
	scala: "#c22d40",
	dart: "#00b4ab",
	elixir: "#6e4a7e",
	sql: "#e38c00",
	r: "#198ce7",
	lua: "#000080",
	svelte: "#ff3e00",
	vue: "#41b883",
	angular: "#c3002f",
	"objective-c": "#438eff",
	hcl: "#5c4ee5",
};

export type BlogPost = {
	slug: string;
	date: string;
	title: string;
	summary: string;
	tags: string[];
};

export const blogPosts: BlogPost[] = [
	{
		slug: "getting-started-with-rust",
		date: "2024-05-10",
		title: "Getting Started with Rust",
		summary: "A beginner's guide to setting up Rust and writing your first program.",
		tags: ["Rust", "Tutorial"],
	},
	{
		slug: "kubernetes-for-developers",
		date: "2024-04-22",
		title: "Kubernetes for Developers",
		summary: "Learn how Kubernetes can simplify deployment and scaling for your applications.",
		tags: ["Kubernetes", "DevOps"],
	},
	{
		slug: "spring-boot-best-practices",
		date: "2024-03-15",
		title: "Spring Boot Best Practices",
		summary: "Tips and tricks for building robust Spring Boot applications.",
		tags: ["Java", "Spring Boot"],
	},
	{
		slug: "grpc-vs-rest",
		date: "2024-02-28",
		title: "gRPC vs REST: Which Should You Choose?",
		summary: "A comparison of gRPC and REST for building modern APIs.",
		tags: ["API", "gRPC"],
	},
	{
		slug: "docker-in-production",
		date: "2024-01-12",
		title: "Docker in Production",
		summary: "Best practices for running Docker containers in production environments.",
		tags: ["Docker", "DevOps"],
	},
];

export type BadgeColors = {
	backgroundColor: string;
	textColor: string;
};

export const languageColors2: Map<string, BadgeColors> = new Map([
	["1c enterprise", { backgroundColor: "#814CCC", textColor: "#ffffff" }],
	["2-dimensional array", { backgroundColor: "#38761D", textColor: "#ffffff" }],
	["4d", { backgroundColor: "#004289", textColor: "#ffffff" }],
	["abap", { backgroundColor: "#E8274B", textColor: "#ffffff" }],
	["abap cds", { backgroundColor: "#555e25", textColor: "#ffffff" }],
	["abnf", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["ags script", { backgroundColor: "#B9D9FF", textColor: "#000000" }],
	["aidl", { backgroundColor: "#34EB6B", textColor: "#000000" }],
	["al", { backgroundColor: "#3AA2B5", textColor: "#000000" }],
	["ampl", { backgroundColor: "#E6EFBB", textColor: "#000000" }],
	["antlr", { backgroundColor: "#9DC3FF", textColor: "#000000" }],
	["api blueprint", { backgroundColor: "#2ACCA8", textColor: "#000000" }],
	["apl", { backgroundColor: "#5A8164", textColor: "#ffffff" }],
	["asl", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["asn.1", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["asp.net", { backgroundColor: "#9400ff", textColor: "#ffffff" }],
	["ats", { backgroundColor: "#1ac620", textColor: "#000000" }],
	["actionscript", { backgroundColor: "#882B0F", textColor: "#ffffff" }],
	["ada", { backgroundColor: "#02f88c", textColor: "#000000" }],
	["adblock filter list", { backgroundColor: "#800000", textColor: "#ffffff" }],
	["adobe font metrics", { backgroundColor: "#fa0f00", textColor: "#ffffff" }],
	["agda", { backgroundColor: "#315665", textColor: "#ffffff" }],
	["aiken", { backgroundColor: "#640ff8", textColor: "#ffffff" }],
	["alloy", { backgroundColor: "#64C800", textColor: "#000000" }],
	["alpine abuild", { backgroundColor: "#0D597F", textColor: "#ffffff" }],
	["altium designer", { backgroundColor: "#A89663", textColor: "#000000" }],
	["angelscript", { backgroundColor: "#C7D7DC", textColor: "#000000" }],
	[
		"answer set programming",
		{ backgroundColor: "#A9CC29", textColor: "#000000" },
	],
	["ant build system", { backgroundColor: "#A9157E", textColor: "#ffffff" }],
	["antlers", { backgroundColor: "#ff269e", textColor: "#ffffff" }],
	["apacheconf", { backgroundColor: "#d12127", textColor: "#ffffff" }],
	["apex", { backgroundColor: "#1797c0", textColor: "#ffffff" }],
	[
		"apollo guidance computer",
		{ backgroundColor: "#0B3D91", textColor: "#ffffff" },
	],
	["applescript", { backgroundColor: "#101F1F", textColor: "#ffffff" }],
	["arc", { backgroundColor: "#aa2afe", textColor: "#ffffff" }],
	["asciidoc", { backgroundColor: "#73a0c5", textColor: "#ffffff" }],
	["aspectj", { backgroundColor: "#a957b0", textColor: "#ffffff" }],
	["assembly", { backgroundColor: "#6E4C13", textColor: "#ffffff" }],
	["astro", { backgroundColor: "#ff5a03", textColor: "#ffffff" }],
	["asymptote", { backgroundColor: "#ff0000", textColor: "#ffffff" }],
	["augeas", { backgroundColor: "#9CC134", textColor: "#000000" }],
	["autohotkey", { backgroundColor: "#6594b9", textColor: "#ffffff" }],
	["autoit", { backgroundColor: "#1C3552", textColor: "#ffffff" }],
	["avro idl", { backgroundColor: "#0040FF", textColor: "#ffffff" }],
	["awk", { backgroundColor: "#c30e9b", textColor: "#ffffff" }],
	["b4x", { backgroundColor: "#00e4ff", textColor: "#000000" }],
	["basic", { backgroundColor: "#ff0000", textColor: "#ffffff" }],
	["bqn", { backgroundColor: "#2b7067", textColor: "#ffffff" }],
	["ballerina", { backgroundColor: "#FF5000", textColor: "#ffffff" }],
	["batchfile", { backgroundColor: "#C1F12E", textColor: "#000000" }],
	["beef", { backgroundColor: "#a52f4e", textColor: "#ffffff" }],
	["befunge", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["berry", { backgroundColor: "#15A13C", textColor: "#ffffff" }],
	["bibtex", { backgroundColor: "#778899", textColor: "#ffffff" }],
	["bibtex style", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["bicep", { backgroundColor: "#519aba", textColor: "#ffffff" }],
	["bikeshed", { backgroundColor: "#5562ac", textColor: "#ffffff" }],
	["bison", { backgroundColor: "#6A463F", textColor: "#ffffff" }],
	["bitbake", { backgroundColor: "#00bce4", textColor: "#000000" }],
	["blade", { backgroundColor: "#f7523f", textColor: "#ffffff" }],
	["blitzbasic", { backgroundColor: "#00FFAE", textColor: "#000000" }],
	["blitzmax", { backgroundColor: "#cd6400", textColor: "#ffffff" }],
	["bluespec", { backgroundColor: "#12223c", textColor: "#ffffff" }],
	["bluespec bh", { backgroundColor: "#12223c", textColor: "#ffffff" }],
	["boo", { backgroundColor: "#d4bec1", textColor: "#000000" }],
	["boogie", { backgroundColor: "#c80fa0", textColor: "#ffffff" }],
	["brainfuck", { backgroundColor: "#2F2530", textColor: "#ffffff" }],
	["brighterscript", { backgroundColor: "#66AABB", textColor: "#000000" }],
	["brightscript", { backgroundColor: "#662D91", textColor: "#ffffff" }],
	["browserslist", { backgroundColor: "#ffd539", textColor: "#000000" }],
	["bru", { backgroundColor: "#F4AA41", textColor: "#000000" }],
	["buildstream", { backgroundColor: "#006bff", textColor: "#ffffff" }],
	["c", { backgroundColor: "#555555", textColor: "#ffffff" }],
	["c#", { backgroundColor: "#178600", textColor: "#ffffff" }],
	["c++", { backgroundColor: "#f34b7d", textColor: "#ffffff" }],
	["c-objdump", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["c2hs haskell", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["c3", { backgroundColor: "#2563eb", textColor: "#ffffff" }],
	["cap cds", { backgroundColor: "#0092d1", textColor: "#ffffff" }],
	["cil", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["clips", { backgroundColor: "#00A300", textColor: "#ffffff" }],
	["cmake", { backgroundColor: "#DA3434", textColor: "#ffffff" }],
	["cobol", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["codeowners", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["collada", { backgroundColor: "#F1A42B", textColor: "#000000" }],
	["cson", { backgroundColor: "#244776", textColor: "#ffffff" }],
	["css", { backgroundColor: "#663399", textColor: "#ffffff" }],
	["csv", { backgroundColor: "#237346", textColor: "#ffffff" }],
	["cue", { backgroundColor: "#5886E1", textColor: "#ffffff" }],
	["cweb", { backgroundColor: "#00007a", textColor: "#ffffff" }],
	["cabal config", { backgroundColor: "#483465", textColor: "#ffffff" }],
	["caddyfile", { backgroundColor: "#22b638", textColor: "#000000" }],
	["cadence", { backgroundColor: "#00ef8b", textColor: "#000000" }],
	["cairo", { backgroundColor: "#ff4a48", textColor: "#ffffff" }],
	["cairo zero", { backgroundColor: "#ff4a48", textColor: "#ffffff" }],
	["cameligo", { backgroundColor: "#3be133", textColor: "#000000" }],
	["cap'n proto", { backgroundColor: "#c42727", textColor: "#ffffff" }],
	["carbon", { backgroundColor: "#222222", textColor: "#ffffff" }],
	["cartocss", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["ceylon", { backgroundColor: "#dfa535", textColor: "#000000" }],
	["chapel", { backgroundColor: "#8dc63f", textColor: "#000000" }],
	["charity", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["checksums", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["chuck", { backgroundColor: "#3f8000", textColor: "#ffffff" }],
	["circom", { backgroundColor: "#707575", textColor: "#ffffff" }],
	["cirru", { backgroundColor: "#ccccff", textColor: "#000000" }],
	["clarion", { backgroundColor: "#db901e", textColor: "#000000" }],
	["clarity", { backgroundColor: "#5546ff", textColor: "#ffffff" }],
	["classic asp", { backgroundColor: "#6a40fd", textColor: "#ffffff" }],
	["clean", { backgroundColor: "#3F85AF", textColor: "#ffffff" }],
	["click", { backgroundColor: "#E4E6F3", textColor: "#000000" }],
	["clojure", { backgroundColor: "#db5855", textColor: "#ffffff" }],
	["closure templates", { backgroundColor: "#0d948f", textColor: "#ffffff" }],
	[
		"cloud firestore security rules",
		{ backgroundColor: "#FFA000", textColor: "#000000" },
	],
	["clue", { backgroundColor: "#0009b5", textColor: "#ffffff" }],
	["conll-u", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["codeql", { backgroundColor: "#140f46", textColor: "#ffffff" }],
	["coffeescript", { backgroundColor: "#244776", textColor: "#ffffff" }],
	["coldfusion", { backgroundColor: "#ed2cd6", textColor: "#ffffff" }],
	["coldfusion cfc", { backgroundColor: "#ed2cd6", textColor: "#ffffff" }],
	["common lisp", { backgroundColor: "#3fb68b", textColor: "#000000" }],
	[
		"common workflow language",
		{ backgroundColor: "#B5314C", textColor: "#ffffff" },
	],
	["component pascal", { backgroundColor: "#B0CE4E", textColor: "#000000" }],
	["cooklang", { backgroundColor: "#E15A29", textColor: "#ffffff" }],
	["cool", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["cpp-objdump", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["creole", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["crystal", { backgroundColor: "#000100", textColor: "#ffffff" }],
	["csound", { backgroundColor: "#1a1a1a", textColor: "#ffffff" }],
	["csound document", { backgroundColor: "#1a1a1a", textColor: "#ffffff" }],
	["csound score", { backgroundColor: "#1a1a1a", textColor: "#ffffff" }],
	["cuda", { backgroundColor: "#3A4E3A", textColor: "#ffffff" }],
	["cue sheet", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["curry", { backgroundColor: "#531242", textColor: "#ffffff" }],
	["cycript", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["cylc", { backgroundColor: "#00b3fd", textColor: "#000000" }],
	["cypher", { backgroundColor: "#34c0eb", textColor: "#000000" }],
	["cython", { backgroundColor: "#fedf5b", textColor: "#000000" }],
	["d", { backgroundColor: "#ba595e", textColor: "#ffffff" }],
	["d-objdump", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["d2", { backgroundColor: "#526ee8", textColor: "#ffffff" }],
	[
		"digital command language",
		{ backgroundColor: "#000000", textColor: "#ffffff" },
	],
	["dm", { backgroundColor: "#447265", textColor: "#ffffff" }],
	["dns zone", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["dtrace", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["dafny", { backgroundColor: "#FFEC25", textColor: "#000000" }],
	["darcs patch", { backgroundColor: "#8eff23", textColor: "#000000" }],
	["dart", { backgroundColor: "#00B4AB", textColor: "#ffffff" }],
	["daslang", { backgroundColor: "#d3d3d3", textColor: "#000000" }],
	["dataweave", { backgroundColor: "#003a52", textColor: "#ffffff" }],
	[
		"debian package control file",
		{ backgroundColor: "#D70751", textColor: "#ffffff" },
	],
	["denizenscript", { backgroundColor: "#FBEE96", textColor: "#000000" }],
	["dhall", { backgroundColor: "#dfafff", textColor: "#000000" }],
	["diff", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["directx 3d file", { backgroundColor: "#aace60", textColor: "#000000" }],
	["dockerfile", { backgroundColor: "#384d54", textColor: "#ffffff" }],
	["dogescript", { backgroundColor: "#cca760", textColor: "#000000" }],
	["dotenv", { backgroundColor: "#e5d559", textColor: "#000000" }],
	["dune", { backgroundColor: "#89421e", textColor: "#ffffff" }],
	["dylan", { backgroundColor: "#6c616e", textColor: "#ffffff" }],
	["e", { backgroundColor: "#ccce35", textColor: "#000000" }],
	["e-mail", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["ebnf", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["ecl", { backgroundColor: "#8a1267", textColor: "#ffffff" }],
	["eclipse", { backgroundColor: "#001d9d", textColor: "#ffffff" }],
	["ejs", { backgroundColor: "#a91e50", textColor: "#ffffff" }],
	["eq", { backgroundColor: "#a78649", textColor: "#000000" }],
	["eagle", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["earthly", { backgroundColor: "#2af0ff", textColor: "#000000" }],
	["easybuild", { backgroundColor: "#069406", textColor: "#ffffff" }],
	["ecere projects", { backgroundColor: "#913960", textColor: "#ffffff" }],
	["ecmarkup", { backgroundColor: "#eb8131", textColor: "#000000" }],
	["edge", { backgroundColor: "#0dffe0", textColor: "#000000" }],
	["edgeql", { backgroundColor: "#31A7FF", textColor: "#000000" }],
	["editorconfig", { backgroundColor: "#fff1f2", textColor: "#000000" }],
	[
		"edje data collection",
		{ backgroundColor: "#000000", textColor: "#ffffff" },
	],
	["eiffel", { backgroundColor: "#4d6977", textColor: "#ffffff" }],
	["elixir", { backgroundColor: "#6e4a7e", textColor: "#ffffff" }],
	["elm", { backgroundColor: "#60B5CC", textColor: "#000000" }],
	["elvish", { backgroundColor: "#55BB55", textColor: "#000000" }],
	["elvish transcript", { backgroundColor: "#55BB55", textColor: "#000000" }],
	["emacs lisp", { backgroundColor: "#c065db", textColor: "#ffffff" }],
	["emberscript", { backgroundColor: "#FFF4F3", textColor: "#000000" }],
	["erlang", { backgroundColor: "#B83998", textColor: "#ffffff" }],
	["euphoria", { backgroundColor: "#FF790B", textColor: "#000000" }],
	["f#", { backgroundColor: "#b845fc", textColor: "#ffffff" }],
	["f*", { backgroundColor: "#572e30", textColor: "#ffffff" }],
	["figlet font", { backgroundColor: "#FFDDBB", textColor: "#000000" }],
	["firrtl", { backgroundColor: "#2f632f", textColor: "#ffffff" }],
	["flux", { backgroundColor: "#88ccff", textColor: "#000000" }],
	["factor", { backgroundColor: "#636746", textColor: "#ffffff" }],
	["fancy", { backgroundColor: "#7b9db4", textColor: "#000000" }],
	["fantom", { backgroundColor: "#14253c", textColor: "#ffffff" }],
	["faust", { backgroundColor: "#c37240", textColor: "#000000" }],
	["fennel", { backgroundColor: "#fff3d7", textColor: "#000000" }],
	["filebench wml", { backgroundColor: "#F6B900", textColor: "#000000" }],
	["filterscript", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["flix", { backgroundColor: "#d44a45", textColor: "#ffffff" }],
	["fluent", { backgroundColor: "#ffcc33", textColor: "#000000" }],
	["formatted", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["forth", { backgroundColor: "#341708", textColor: "#ffffff" }],
	["fortran", { backgroundColor: "#4d41b1", textColor: "#ffffff" }],
	["fortran free form", { backgroundColor: "#4d41b1", textColor: "#ffffff" }],
	["freebasic", { backgroundColor: "#141AC9", textColor: "#ffffff" }],
	["freemarker", { backgroundColor: "#0050b2", textColor: "#ffffff" }],
	["frege", { backgroundColor: "#00cafe", textColor: "#000000" }],
	["futhark", { backgroundColor: "#5f021f", textColor: "#ffffff" }],
	["g-code", { backgroundColor: "#D08CF2", textColor: "#000000" }],
	["gaml", { backgroundColor: "#FFC766", textColor: "#000000" }],
	["gams", { backgroundColor: "#f49a22", textColor: "#000000" }],
	["gap", { backgroundColor: "#0000cc", textColor: "#ffffff" }],
	[
		"gcc machine description",
		{ backgroundColor: "#FFCFAB", textColor: "#000000" },
	],
	["gdb", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["gdscript", { backgroundColor: "#355570", textColor: "#ffffff" }],
	["gdshader", { backgroundColor: "#478CBF", textColor: "#ffffff" }],
	["gedcom", { backgroundColor: "#003058", textColor: "#ffffff" }],
	["glsl", { backgroundColor: "#5686a5", textColor: "#ffffff" }],
	["gn", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["gsc", { backgroundColor: "#FF6800", textColor: "#ffffff" }],
	["game maker language", { backgroundColor: "#71b417", textColor: "#000000" }],
	["gemfile.lock", { backgroundColor: "#701516", textColor: "#ffffff" }],
	["gemini", { backgroundColor: "#ff6900", textColor: "#ffffff" }],
	["genero 4gl", { backgroundColor: "#63408e", textColor: "#ffffff" }],
	["genero per", { backgroundColor: "#d8df39", textColor: "#000000" }],
	["genie", { backgroundColor: "#fb855d", textColor: "#000000" }],
	["genshi", { backgroundColor: "#951531", textColor: "#ffffff" }],
	["gentoo ebuild", { backgroundColor: "#9400ff", textColor: "#ffffff" }],
	["gentoo eclass", { backgroundColor: "#9400ff", textColor: "#ffffff" }],
	["gerber image", { backgroundColor: "#d20b00", textColor: "#ffffff" }],
	["gettext catalog", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["gherkin", { backgroundColor: "#5B2063", textColor: "#ffffff" }],
	["git attributes", { backgroundColor: "#F44D27", textColor: "#ffffff" }],
	["git config", { backgroundColor: "#F44D27", textColor: "#ffffff" }],
	["git revision list", { backgroundColor: "#F44D27", textColor: "#ffffff" }],
	["gleam", { backgroundColor: "#ffaff3", textColor: "#000000" }],
	["glimmer js", { backgroundColor: "#F5835F", textColor: "#000000" }],
	["glimmer ts", { backgroundColor: "#3178c6", textColor: "#ffffff" }],
	["glyph", { backgroundColor: "#c1ac7f", textColor: "#000000" }],
	[
		"glyph bitmap distribution format",
		{ backgroundColor: "#000000", textColor: "#ffffff" },
	],
	["gnuplot", { backgroundColor: "#f0a9f0", textColor: "#000000" }],
	["go", { backgroundColor: "#00ADD8", textColor: "#000000" }],
	["go checksums", { backgroundColor: "#00ADD8", textColor: "#000000" }],
	["go module", { backgroundColor: "#00ADD8", textColor: "#000000" }],
	["go workspace", { backgroundColor: "#00ADD8", textColor: "#000000" }],
	["godot resource", { backgroundColor: "#355570", textColor: "#ffffff" }],
	["golo", { backgroundColor: "#88562A", textColor: "#ffffff" }],
	["gosu", { backgroundColor: "#82937f", textColor: "#000000" }],
	["grace", { backgroundColor: "#615f8b", textColor: "#ffffff" }],
	["gradle", { backgroundColor: "#02303a", textColor: "#ffffff" }],
	["gradle kotlin dsl", { backgroundColor: "#02303a", textColor: "#ffffff" }],
	[
		"grammatical framework",
		{ backgroundColor: "#ff0000", textColor: "#ffffff" },
	],
	[
		"graph modeling language",
		{ backgroundColor: "#000000", textColor: "#ffffff" },
	],
	["graphql", { backgroundColor: "#e10098", textColor: "#ffffff" }],
	["graphviz (dot)", { backgroundColor: "#2596be", textColor: "#ffffff" }],
	["groovy", { backgroundColor: "#4298b8", textColor: "#ffffff" }],
	["groovy server pages", { backgroundColor: "#4298b8", textColor: "#ffffff" }],
	["haproxy", { backgroundColor: "#106da9", textColor: "#ffffff" }],
	["hcl", { backgroundColor: "#844FBA", textColor: "#ffffff" }],
	["hip", { backgroundColor: "#4F3A4F", textColor: "#ffffff" }],
	["hlsl", { backgroundColor: "#aace60", textColor: "#000000" }],
	["hocon", { backgroundColor: "#9ff8ee", textColor: "#000000" }],
	["html", { backgroundColor: "#e34c26", textColor: "#ffffff" }],
	["html+ecr", { backgroundColor: "#2e1052", textColor: "#ffffff" }],
	["html+eex", { backgroundColor: "#6e4a7e", textColor: "#ffffff" }],
	["html+erb", { backgroundColor: "#701516", textColor: "#ffffff" }],
	["html+php", { backgroundColor: "#4f5d95", textColor: "#ffffff" }],
	["html+razor", { backgroundColor: "#512be4", textColor: "#ffffff" }],
	["http", { backgroundColor: "#005C9C", textColor: "#ffffff" }],
	["hxml", { backgroundColor: "#f68712", textColor: "#000000" }],
	["hack", { backgroundColor: "#878787", textColor: "#ffffff" }],
	["haml", { backgroundColor: "#ece2a9", textColor: "#000000" }],
	["handlebars", { backgroundColor: "#f7931e", textColor: "#000000" }],
	["harbour", { backgroundColor: "#0e60e3", textColor: "#ffffff" }],
	["hare", { backgroundColor: "#9d7424", textColor: "#ffffff" }],
	["haskell", { backgroundColor: "#5e5086", textColor: "#ffffff" }],
	["haxe", { backgroundColor: "#df7900", textColor: "#ffffff" }],
	["hiveql", { backgroundColor: "#dce200", textColor: "#000000" }],
	["holyc", { backgroundColor: "#ffefaf", textColor: "#000000" }],
	["hosts file", { backgroundColor: "#308888", textColor: "#ffffff" }],
	["hy", { backgroundColor: "#7790B2", textColor: "#ffffff" }],
	["hyphy", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["idl", { backgroundColor: "#a3522f", textColor: "#ffffff" }],
	["igor pro", { backgroundColor: "#0000cc", textColor: "#ffffff" }],
	["ini", { backgroundColor: "#d1dbe0", textColor: "#000000" }],
	["irc log", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["ispc", { backgroundColor: "#2D68B1", textColor: "#ffffff" }],
	["idris", { backgroundColor: "#b30000", textColor: "#ffffff" }],
	["ignore list", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["imagej macro", { backgroundColor: "#99AAFF", textColor: "#000000" }],
	["imba", { backgroundColor: "#16cec6", textColor: "#000000" }],
	["inform 7", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["ink", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["inno setup", { backgroundColor: "#264b99", textColor: "#ffffff" }],
	["io", { backgroundColor: "#a9188d", textColor: "#ffffff" }],
	["ioke", { backgroundColor: "#078193", textColor: "#ffffff" }],
	["isabelle", { backgroundColor: "#FEFE00", textColor: "#000000" }],
	["isabelle root", { backgroundColor: "#FEFE00", textColor: "#000000" }],
	["j", { backgroundColor: "#9EEDFF", textColor: "#000000" }],
	["jar manifest", { backgroundColor: "#b07219", textColor: "#ffffff" }],
	["jcl", { backgroundColor: "#d90e09", textColor: "#ffffff" }],
	["jflex", { backgroundColor: "#DBCA00", textColor: "#000000" }],
	["json", { backgroundColor: "#292929", textColor: "#ffffff" }],
	["json with comments", { backgroundColor: "#292929", textColor: "#ffffff" }],
	["json5", { backgroundColor: "#267CB9", textColor: "#ffffff" }],
	["jsonld", { backgroundColor: "#0c479c", textColor: "#ffffff" }],
	["jsoniq", { backgroundColor: "#40d47e", textColor: "#000000" }],
	["jai", { backgroundColor: "#ab8b4b", textColor: "#ffffff" }],
	["janet", { backgroundColor: "#0886a5", textColor: "#ffffff" }],
	["jasmin", { backgroundColor: "#d03600", textColor: "#ffffff" }],
	["java", { backgroundColor: "#b07219", textColor: "#ffffff" }],
	["java properties", { backgroundColor: "#2A6277", textColor: "#ffffff" }],
	["java server pages", { backgroundColor: "#2A6277", textColor: "#ffffff" }],
	[
		"java template engine",
		{ backgroundColor: "#2A6277", textColor: "#ffffff" },
	],
	["javascript", { backgroundColor: "#f1e05a", textColor: "#000000" }],
	["javascript+erb", { backgroundColor: "#f1e05a", textColor: "#000000" }],
	["jest snapshot", { backgroundColor: "#15c213", textColor: "#000000" }],
	["jetbrains mps", { backgroundColor: "#21D789", textColor: "#000000" }],
	["jinja", { backgroundColor: "#a52a22", textColor: "#ffffff" }],
	["jison", { backgroundColor: "#56b3cb", textColor: "#000000" }],
	["jison lex", { backgroundColor: "#56b3cb", textColor: "#000000" }],
	["jolie", { backgroundColor: "#843179", textColor: "#ffffff" }],
	["jsonnet", { backgroundColor: "#0064bd", textColor: "#ffffff" }],
	["julia", { backgroundColor: "#a270ba", textColor: "#ffffff" }],
	["julia repl", { backgroundColor: "#a270ba", textColor: "#ffffff" }],
	["jupyter notebook", { backgroundColor: "#DA5B0B", textColor: "#ffffff" }],
	["just", { backgroundColor: "#384d54", textColor: "#ffffff" }],
	["kdl", { backgroundColor: "#ffb3b3", textColor: "#000000" }],
	["krl", { backgroundColor: "#28430A", textColor: "#ffffff" }],
	["kaitai struct", { backgroundColor: "#773b37", textColor: "#ffffff" }],
	["kakounescript", { backgroundColor: "#6f8042", textColor: "#ffffff" }],
	["kerboscript", { backgroundColor: "#41adf0", textColor: "#000000" }],
	["kicad layout", { backgroundColor: "#2f4aab", textColor: "#ffffff" }],
	["kicad legacy layout", { backgroundColor: "#2f4aab", textColor: "#ffffff" }],
	["kicad schematic", { backgroundColor: "#2f4aab", textColor: "#ffffff" }],
	["kickstart", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["kit", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["kolmafia ash", { backgroundColor: "#B9D9B9", textColor: "#000000" }],
	["koka", { backgroundColor: "#215166", textColor: "#ffffff" }],
	["kotlin", { backgroundColor: "#A97BFF", textColor: "#000000" }],
	["kusto", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["lfe", { backgroundColor: "#4C3023", textColor: "#ffffff" }],
	["llvm", { backgroundColor: "#185619", textColor: "#ffffff" }],
	["lolcode", { backgroundColor: "#cc9900", textColor: "#000000" }],
	["lsl", { backgroundColor: "#3d9970", textColor: "#ffffff" }],
	["ltspice symbol", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["labview", { backgroundColor: "#fede06", textColor: "#000000" }],
	["lark", { backgroundColor: "#2980B9", textColor: "#ffffff" }],
	["lasso", { backgroundColor: "#999999", textColor: "#000000" }],
	["latte", { backgroundColor: "#f2a542", textColor: "#000000" }],
	["lean", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["lean 4", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["leo", { backgroundColor: "#C4FFC2", textColor: "#000000" }],
	["less", { backgroundColor: "#1d365d", textColor: "#ffffff" }],
	["lex", { backgroundColor: "#DBCA00", textColor: "#000000" }],
	["ligolang", { backgroundColor: "#0e74ff", textColor: "#ffffff" }],
	["lilypond", { backgroundColor: "#9ccc7c", textColor: "#000000" }],
	["limbo", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["linear programming", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["linker script", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["linux kernel module", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["liquid", { backgroundColor: "#67b8de", textColor: "#000000" }],
	["literate agda", { backgroundColor: "#315665", textColor: "#ffffff" }],
	[
		"literate coffeescript",
		{ backgroundColor: "#244776", textColor: "#ffffff" },
	],
	["literate haskell", { backgroundColor: "#5e5086", textColor: "#ffffff" }],
	["livecode script", { backgroundColor: "#0c5ba5", textColor: "#ffffff" }],
	["livescript", { backgroundColor: "#499886", textColor: "#ffffff" }],
	["logos", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["logtalk", { backgroundColor: "#295b9a", textColor: "#ffffff" }],
	["lookml", { backgroundColor: "#652B81", textColor: "#ffffff" }],
	["loomscript", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["lua", { backgroundColor: "#000080", textColor: "#ffffff" }],
	["luau", { backgroundColor: "#00A2FF", textColor: "#000000" }],
	["m", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["m3u", { backgroundColor: "#179C7D", textColor: "#000000" }],
	["m4", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["m4sugar", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["matlab", { backgroundColor: "#e16737", textColor: "#ffffff" }],
	["maxscript", { backgroundColor: "#00a6a6", textColor: "#ffffff" }],
	["mdx", { backgroundColor: "#fcb32c", textColor: "#000000" }],
	["mlir", { backgroundColor: "#5EC8DB", textColor: "#000000" }],
	["mql4", { backgroundColor: "#62A8D6", textColor: "#000000" }],
	["mql5", { backgroundColor: "#4A76B8", textColor: "#ffffff" }],
	["mtml", { backgroundColor: "#b7e1f4", textColor: "#000000" }],
	["muf", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["macaulay2", { backgroundColor: "#d8ffff", textColor: "#000000" }],
	["makefile", { backgroundColor: "#427819", textColor: "#ffffff" }],
	["mako", { backgroundColor: "#7e858d", textColor: "#ffffff" }],
	["markdown", { backgroundColor: "#083fa1", textColor: "#ffffff" }],
	["marko", { backgroundColor: "#42bff2", textColor: "#000000" }],
	["mask", { backgroundColor: "#f97732", textColor: "#ffffff" }],
	["mathematica", { backgroundColor: "#dd1100", textColor: "#ffffff" }],
	["maven pom", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["max", { backgroundColor: "#c4a79c", textColor: "#000000" }],
	["mercury", { backgroundColor: "#ff2b2b", textColor: "#ffffff" }],
	["mermaid", { backgroundColor: "#ff3670", textColor: "#ffffff" }],
	["meson", { backgroundColor: "#007800", textColor: "#ffffff" }],
	["metal", { backgroundColor: "#8f14e9", textColor: "#ffffff" }],
	[
		"microsoft developer studio project",
		{ backgroundColor: "#000000", textColor: "#ffffff" },
	],
	[
		"microsoft visual studio solution",
		{ backgroundColor: "#000000", textColor: "#ffffff" },
	],
	["minid", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["miniyaml", { backgroundColor: "#ff1111", textColor: "#ffffff" }],
	["minizinc", { backgroundColor: "#06a9e6", textColor: "#ffffff" }],
	["minizinc data", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["mint", { backgroundColor: "#02b046", textColor: "#ffffff" }],
	["mirah", { backgroundColor: "#c7a938", textColor: "#000000" }],
	["modelica", { backgroundColor: "#de1d31", textColor: "#ffffff" }],
	["modula-2", { backgroundColor: "#10253f", textColor: "#ffffff" }],
	["modula-3", { backgroundColor: "#223388", textColor: "#ffffff" }],
	[
		"module management system",
		{ backgroundColor: "#000000", textColor: "#ffffff" },
	],
	["mojo", { backgroundColor: "#ff4c1f", textColor: "#ffffff" }],
	["monkey", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["monkey c", { backgroundColor: "#8D6747", textColor: "#ffffff" }],
	["moocode", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["moonbit", { backgroundColor: "#b92381", textColor: "#ffffff" }],
	["moonscript", { backgroundColor: "#ff4585", textColor: "#ffffff" }],
	["motoko", { backgroundColor: "#fbb03b", textColor: "#000000" }],
	[
		"motorola 68k assembly",
		{ backgroundColor: "#005daa", textColor: "#ffffff" },
	],
	["move", { backgroundColor: "#4a137a", textColor: "#ffffff" }],
	["muse", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["mustache", { backgroundColor: "#724b3b", textColor: "#ffffff" }],
	["myghty", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["nasl", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["ncl", { backgroundColor: "#28431f", textColor: "#ffffff" }],
	["neon", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["nl", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["nmodl", { backgroundColor: "#00356B", textColor: "#ffffff" }],
	["npm config", { backgroundColor: "#cb3837", textColor: "#ffffff" }],
	["nsis", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["nwscript", { backgroundColor: "#111522", textColor: "#ffffff" }],
	["nasal", { backgroundColor: "#1d2c4e", textColor: "#ffffff" }],
	["nearley", { backgroundColor: "#990000", textColor: "#ffffff" }],
	["nemerle", { backgroundColor: "#3d3c6e", textColor: "#ffffff" }],
	["netlinx", { backgroundColor: "#0aa0ff", textColor: "#000000" }],
	["netlinx+erb", { backgroundColor: "#747faa", textColor: "#ffffff" }],
	["netlogo", { backgroundColor: "#ff6375", textColor: "#ffffff" }],
	["newlisp", { backgroundColor: "#87AED7", textColor: "#000000" }],
	["nextflow", { backgroundColor: "#3ac486", textColor: "#000000" }],
	["nginx", { backgroundColor: "#009639", textColor: "#ffffff" }],
	["nickel", { backgroundColor: "#E0C3FC", textColor: "#000000" }],
	["nim", { backgroundColor: "#ffc200", textColor: "#000000" }],
	["ninja", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["nit", { backgroundColor: "#009917", textColor: "#ffffff" }],
	["nix", { backgroundColor: "#7e7eff", textColor: "#ffffff" }],
	["noir", { backgroundColor: "#2f1f49", textColor: "#ffffff" }],
	["nu", { backgroundColor: "#c9df40", textColor: "#000000" }],
	["numpy", { backgroundColor: "#9C8AF9", textColor: "#000000" }],
	["nunjucks", { backgroundColor: "#3d8137", textColor: "#ffffff" }],
	["nushell", { backgroundColor: "#4E9906", textColor: "#ffffff" }],
	["ocaml", { backgroundColor: "#ef7a08", textColor: "#000000" }],
	["omnet++ msg", { backgroundColor: "#a0e0a0", textColor: "#000000" }],
	["omnet++ ned", { backgroundColor: "#08607c", textColor: "#ffffff" }],
	["oberon", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["objdump", { backgroundColor: "#000000", textColor: "#ffffff" }],
	[
		"object data instance notation",
		{ backgroundColor: "#000000", textColor: "#ffffff" },
	],
	["objectscript", { backgroundColor: "#424893", textColor: "#ffffff" }],
	["objective-c", { backgroundColor: "#438eff", textColor: "#ffffff" }],
	["objective-c++", { backgroundColor: "#6866fb", textColor: "#ffffff" }],
	["objective-j", { backgroundColor: "#ff0c5a", textColor: "#ffffff" }],
	["odin", { backgroundColor: "#60AFFE", textColor: "#000000" }],
	["omgrofl", { backgroundColor: "#cabbff", textColor: "#000000" }],
	["opa", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["opal", { backgroundColor: "#f7ede0", textColor: "#000000" }],
	["open policy agent", { backgroundColor: "#7d9199", textColor: "#ffffff" }],
	["opencl", { backgroundColor: "#ed2e2d", textColor: "#ffffff" }],
	["openedge abl", { backgroundColor: "#5ce600", textColor: "#000000" }],
	["openqasm", { backgroundColor: "#AA70FF", textColor: "#ffffff" }],
	["openrc runscript", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["openscad", { backgroundColor: "#e5cd45", textColor: "#000000" }],
	[
		"openstep property list",
		{ backgroundColor: "#000000", textColor: "#ffffff" },
	],
	[
		"opentype feature file",
		{ backgroundColor: "#000000", textColor: "#ffffff" },
	],
	["option list", { backgroundColor: "#476732", textColor: "#ffffff" }],
	["org", { backgroundColor: "#77aa99", textColor: "#000000" }],
	["overpassql", { backgroundColor: "#cce2aa", textColor: "#000000" }],
	["ox", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["oxygene", { backgroundColor: "#cdd0e3", textColor: "#000000" }],
	["oz", { backgroundColor: "#fab738", textColor: "#000000" }],
	["p4", { backgroundColor: "#7055b5", textColor: "#ffffff" }],
	["pddl", { backgroundColor: "#0d00ff", textColor: "#ffffff" }],
	["peg.js", { backgroundColor: "#234d6b", textColor: "#ffffff" }],
	["php", { backgroundColor: "#4F5D95", textColor: "#ffffff" }],
	["plsql", { backgroundColor: "#dad8d8", textColor: "#000000" }],
	["plpgsql", { backgroundColor: "#336790", textColor: "#ffffff" }],
	["pov-ray sdl", { backgroundColor: "#6bac65", textColor: "#000000" }],
	["pact", { backgroundColor: "#F7A8B8", textColor: "#000000" }],
	["pan", { backgroundColor: "#cc0000", textColor: "#ffffff" }],
	["papyrus", { backgroundColor: "#6600cc", textColor: "#ffffff" }],
	["parrot", { backgroundColor: "#f3ca0a", textColor: "#000000" }],
	["parrot assembly", { backgroundColor: "#000000", textColor: "#ffffff" }],
	[
		"parrot internal representation",
		{ backgroundColor: "#000000", textColor: "#ffffff" },
	],
	["pascal", { backgroundColor: "#E3F171", textColor: "#000000" }],
	["pawn", { backgroundColor: "#dbb284", textColor: "#000000" }],
	["pep8", { backgroundColor: "#C76F5B", textColor: "#ffffff" }],
	["perl", { backgroundColor: "#0298c3", textColor: "#ffffff" }],
	["pic", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["pickle", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["picolisp", { backgroundColor: "#6067af", textColor: "#ffffff" }],
	["piglatin", { backgroundColor: "#fcd7de", textColor: "#000000" }],
	["pike", { backgroundColor: "#005390", textColor: "#ffffff" }],
	["pip requirements", { backgroundColor: "#FFD343", textColor: "#000000" }],
	["pkl", { backgroundColor: "#6b9543", textColor: "#ffffff" }],
	["plantuml", { backgroundColor: "#fbbd16", textColor: "#000000" }],
	["pod", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["pod 6", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["pogoscript", { backgroundColor: "#d80074", textColor: "#ffffff" }],
	["polar", { backgroundColor: "#ae81ff", textColor: "#000000" }],
	["pony", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["portugol", { backgroundColor: "#f8bd00", textColor: "#000000" }],
	["postcss", { backgroundColor: "#dc3a0c", textColor: "#ffffff" }],
	["postscript", { backgroundColor: "#da291c", textColor: "#ffffff" }],
	["powerbuilder", { backgroundColor: "#8f0f8d", textColor: "#ffffff" }],
	["powershell", { backgroundColor: "#012456", textColor: "#ffffff" }],
	["praat", { backgroundColor: "#c8506d", textColor: "#ffffff" }],
	["prisma", { backgroundColor: "#0c344b", textColor: "#ffffff" }],
	["processing", { backgroundColor: "#0096D8", textColor: "#ffffff" }],
	["procfile", { backgroundColor: "#3B2F63", textColor: "#ffffff" }],
	["proguard", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["prolog", { backgroundColor: "#74283c", textColor: "#ffffff" }],
	["promela", { backgroundColor: "#de0000", textColor: "#ffffff" }],
	["propeller spin", { backgroundColor: "#7fa2a7", textColor: "#000000" }],
	["protocol buffer", { backgroundColor: "#000000", textColor: "#ffffff" }],
	[
		"protocol buffer text format",
		{ backgroundColor: "#000000", textColor: "#ffffff" },
	],
	["public key", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["pug", { backgroundColor: "#a86454", textColor: "#ffffff" }],
	["puppet", { backgroundColor: "#302B6D", textColor: "#ffffff" }],
	["pure data", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["purebasic", { backgroundColor: "#5a6986", textColor: "#ffffff" }],
	["purescript", { backgroundColor: "#1D222D", textColor: "#ffffff" }],
	["pyret", { backgroundColor: "#ee1e10", textColor: "#ffffff" }],
	["python", { backgroundColor: "#3572A5", textColor: "#ffffff" }],
	["python console", { backgroundColor: "#3572A5", textColor: "#ffffff" }],
	["python traceback", { backgroundColor: "#3572A5", textColor: "#ffffff" }],
	["q#", { backgroundColor: "#fed659", textColor: "#000000" }],
	["qml", { backgroundColor: "#44a51c", textColor: "#ffffff" }],
	["qmake", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["qt script", { backgroundColor: "#00b841", textColor: "#ffffff" }],
	["quake", { backgroundColor: "#882233", textColor: "#ffffff" }],
	["quakec", { backgroundColor: "#975777", textColor: "#ffffff" }],
	["quickbasic", { backgroundColor: "#008080", textColor: "#ffffff" }],
	["r", { backgroundColor: "#198CE7", textColor: "#ffffff" }],
	["raml", { backgroundColor: "#77d9fb", textColor: "#000000" }],
	["rbs", { backgroundColor: "#701516", textColor: "#ffffff" }],
	["rdoc", { backgroundColor: "#701516", textColor: "#ffffff" }],
	["realbasic", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["rexx", { backgroundColor: "#d90e09", textColor: "#ffffff" }],
	["rmarkdown", { backgroundColor: "#198ce7", textColor: "#ffffff" }],
	["ron", { backgroundColor: "#a62c00", textColor: "#ffffff" }],
	["ros interface", { backgroundColor: "#22314e", textColor: "#ffffff" }],
	["rpc", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["rpgle", { backgroundColor: "#2BDE21", textColor: "#000000" }],
	["rpm spec", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["runoff", { backgroundColor: "#665a4e", textColor: "#ffffff" }],
	["racket", { backgroundColor: "#3c5caa", textColor: "#ffffff" }],
	["ragel", { backgroundColor: "#9d5200", textColor: "#ffffff" }],
	["raku", { backgroundColor: "#0000fb", textColor: "#ffffff" }],
	["rascal", { backgroundColor: "#fffaa0", textColor: "#000000" }],
	["raw token data", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["rescript", { backgroundColor: "#ed5051", textColor: "#ffffff" }],
	["readline config", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["reason", { backgroundColor: "#ff5847", textColor: "#ffffff" }],
	["reasonligo", { backgroundColor: "#ff5847", textColor: "#ffffff" }],
	["rebol", { backgroundColor: "#358a5b", textColor: "#ffffff" }],
	["record jar", { backgroundColor: "#0673ba", textColor: "#ffffff" }],
	["red", { backgroundColor: "#f50000", textColor: "#ffffff" }],
	["redcode", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["redirect rules", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["regular expression", { backgroundColor: "#009a00", textColor: "#ffffff" }],
	["ren'py", { backgroundColor: "#ff7f7f", textColor: "#000000" }],
	["renderscript", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["rez", { backgroundColor: "#FFDAB3", textColor: "#000000" }],
	["rich text format", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["ring", { backgroundColor: "#2D54CB", textColor: "#ffffff" }],
	["riot", { backgroundColor: "#A71E49", textColor: "#ffffff" }],
	["robotframework", { backgroundColor: "#00c0b5", textColor: "#000000" }],
	["roc", { backgroundColor: "#7c38f5", textColor: "#ffffff" }],
	["rocq prover", { backgroundColor: "#d0b68c", textColor: "#000000" }],
	["roff", { backgroundColor: "#ecdebe", textColor: "#000000" }],
	["roff manpage", { backgroundColor: "#ecdebe", textColor: "#000000" }],
	["rouge", { backgroundColor: "#cc0088", textColor: "#ffffff" }],
	["routeros script", { backgroundColor: "#DE3941", textColor: "#ffffff" }],
	["ruby", { backgroundColor: "#701516", textColor: "#ffffff" }],
	["rust", { backgroundColor: "#dea584", textColor: "#ffffff" }],
	["sas", { backgroundColor: "#B34936", textColor: "#ffffff" }],
	["scss", { backgroundColor: "#c6538c", textColor: "#ffffff" }],
	["selinux policy", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["smt", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["sparql", { backgroundColor: "#0C4597", textColor: "#ffffff" }],
	["sqf", { backgroundColor: "#3F3F3F", textColor: "#ffffff" }],
	["sql", { backgroundColor: "#e38c00", textColor: "#ffffff" }],
	["sqlpl", { backgroundColor: "#e38c00", textColor: "#ffffff" }],
	["srecode template", { backgroundColor: "#348a34", textColor: "#ffffff" }],
	["ssh config", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["star", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["stl", { backgroundColor: "#373b5e", textColor: "#ffffff" }],
	["ston", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["svg", { backgroundColor: "#ff9900", textColor: "#000000" }],
	["swig", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["sage", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["sail", { backgroundColor: "#259dd5", textColor: "#ffffff" }],
	["saltstack", { backgroundColor: "#646464", textColor: "#ffffff" }],
	["sass", { backgroundColor: "#a53b70", textColor: "#ffffff" }],
	["scala", { backgroundColor: "#c22d40", textColor: "#ffffff" }],
	["scaml", { backgroundColor: "#bd181a", textColor: "#ffffff" }],
	["scenic", { backgroundColor: "#fdc700", textColor: "#000000" }],
	["scheme", { backgroundColor: "#1e4aec", textColor: "#ffffff" }],
	["scilab", { backgroundColor: "#ca0f21", textColor: "#ffffff" }],
	["self", { backgroundColor: "#0579aa", textColor: "#ffffff" }],
	["shaderlab", { backgroundColor: "#222c37", textColor: "#ffffff" }],
	["shell", { backgroundColor: "#89e051", textColor: "#000000" }],
	["shellcheck config", { backgroundColor: "#cecfcb", textColor: "#000000" }],
	["shellsession", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["shen", { backgroundColor: "#120F14", textColor: "#ffffff" }],
	["sieve", { backgroundColor: "#000000", textColor: "#ffffff" }],
	[
		"simple file verification",
		{ backgroundColor: "#C9BFED", textColor: "#000000" },
	],
	["singularity", { backgroundColor: "#64E6AD", textColor: "#000000" }],
	["slang", { backgroundColor: "#1fbec9", textColor: "#000000" }],
	["slash", { backgroundColor: "#007eff", textColor: "#ffffff" }],
	["slice", { backgroundColor: "#003fa2", textColor: "#ffffff" }],
	["slim", { backgroundColor: "#2b2b2b", textColor: "#ffffff" }],
	["slint", { backgroundColor: "#2379F4", textColor: "#ffffff" }],
	["smpl", { backgroundColor: "#c94949", textColor: "#ffffff" }],
	["smali", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["smalltalk", { backgroundColor: "#596706", textColor: "#ffffff" }],
	["smarty", { backgroundColor: "#f0c040", textColor: "#000000" }],
	["smithy", { backgroundColor: "#c44536", textColor: "#ffffff" }],
	["snakemake", { backgroundColor: "#419179", textColor: "#ffffff" }],
	["solidity", { backgroundColor: "#AA6746", textColor: "#ffffff" }],
	["soong", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["sourcepawn", { backgroundColor: "#f69e1d", textColor: "#000000" }],
	[
		"spline font database",
		{ backgroundColor: "#000000", textColor: "#ffffff" },
	],
	["squirrel", { backgroundColor: "#800000", textColor: "#ffffff" }],
	["stan", { backgroundColor: "#b2011d", textColor: "#ffffff" }],
	["standard ml", { backgroundColor: "#dc566d", textColor: "#ffffff" }],
	["starlark", { backgroundColor: "#76d275", textColor: "#000000" }],
	["stata", { backgroundColor: "#1a5f91", textColor: "#ffffff" }],
	["stringtemplate", { backgroundColor: "#3fb34f", textColor: "#000000" }],
	["stylus", { backgroundColor: "#ff6347", textColor: "#ffffff" }],
	["subrip text", { backgroundColor: "#9e0101", textColor: "#ffffff" }],
	["sugarss", { backgroundColor: "#2fcc9f", textColor: "#000000" }],
	["supercollider", { backgroundColor: "#46390b", textColor: "#ffffff" }],
	["survex data", { backgroundColor: "#ffcc99", textColor: "#000000" }],
	["svelte", { backgroundColor: "#ff3e00", textColor: "#ffffff" }],
	["sway", { backgroundColor: "#00F58C", textColor: "#000000" }],
	["sweave", { backgroundColor: "#198ce7", textColor: "#ffffff" }],
	["swift", { backgroundColor: "#F05138", textColor: "#ffffff" }],
	["systemverilog", { backgroundColor: "#DAE1C2", textColor: "#000000" }],
	["ti program", { backgroundColor: "#A0AA87", textColor: "#000000" }],
	["tl-verilog", { backgroundColor: "#C40023", textColor: "#ffffff" }],
	["tla", { backgroundColor: "#4b0079", textColor: "#ffffff" }],
	["toml", { backgroundColor: "#9c4221", textColor: "#ffffff" }],
	["tsplib data", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["tsql", { backgroundColor: "#e38c00", textColor: "#ffffff" }],
	["tsv", { backgroundColor: "#237346", textColor: "#ffffff" }],
	["tsx", { backgroundColor: "#3178c6", textColor: "#ffffff" }],
	["txl", { backgroundColor: "#0178b8", textColor: "#ffffff" }],
	["tact", { backgroundColor: "#48b5ff", textColor: "#000000" }],
	["talon", { backgroundColor: "#333333", textColor: "#ffffff" }],
	["tcl", { backgroundColor: "#e4cc98", textColor: "#000000" }],
	["tcsh", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["tex", { backgroundColor: "#3D6117", textColor: "#ffffff" }],
	["tea", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["terra", { backgroundColor: "#00004c", textColor: "#ffffff" }],
	["terraform template", { backgroundColor: "#7b42bb", textColor: "#ffffff" }],
	["texinfo", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["text", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["textgrid", { backgroundColor: "#c8506d", textColor: "#ffffff" }],
	["textmate properties", { backgroundColor: "#df66e4", textColor: "#000000" }],
	["textile", { backgroundColor: "#ffe7ac", textColor: "#000000" }],
	["thrift", { backgroundColor: "#D12127", textColor: "#ffffff" }],
	["toit", { backgroundColor: "#c2c9fb", textColor: "#000000" }],
	["tor config", { backgroundColor: "#59316b", textColor: "#ffffff" }],
	["tree-sitter query", { backgroundColor: "#8ea64c", textColor: "#000000" }],
	["turing", { backgroundColor: "#cf142b", textColor: "#ffffff" }],
	["turtle", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["twig", { backgroundColor: "#c1d026", textColor: "#000000" }],
	["type language", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["typescript", { backgroundColor: "#3178c6", textColor: "#ffffff" }],
	["typespec", { backgroundColor: "#4A3665", textColor: "#ffffff" }],
	["typst", { backgroundColor: "#239dad", textColor: "#ffffff" }],
	["unified parallel c", { backgroundColor: "#4e3617", textColor: "#ffffff" }],
	["unity3d asset", { backgroundColor: "#222c37", textColor: "#ffffff" }],
	["unix assembly", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["uno", { backgroundColor: "#9933cc", textColor: "#ffffff" }],
	["unrealscript", { backgroundColor: "#a54c4d", textColor: "#ffffff" }],
	["untyped plutus core", { backgroundColor: "#36adbd", textColor: "#000000" }],
	["urweb", { backgroundColor: "#ccccee", textColor: "#000000" }],
	["v", { backgroundColor: "#4f87c4", textColor: "#ffffff" }],
	["vba", { backgroundColor: "#867db1", textColor: "#000000" }],
	["vbscript", { backgroundColor: "#15dcdc", textColor: "#000000" }],
	["vcl", { backgroundColor: "#148AA8", textColor: "#ffffff" }],
	["vhdl", { backgroundColor: "#adb2cb", textColor: "#000000" }],
	["vala", { backgroundColor: "#a56de2", textColor: "#ffffff" }],
	["valve data format", { backgroundColor: "#f26025", textColor: "#ffffff" }],
	[
		"velocity template language",
		{ backgroundColor: "#507cff", textColor: "#ffffff" },
	],
	["vento", { backgroundColor: "#ff0080", textColor: "#ffffff" }],
	["verilog", { backgroundColor: "#b2b7f8", textColor: "#000000" }],
	["vim help file", { backgroundColor: "#199f4b", textColor: "#000000" }],
	["vim script", { backgroundColor: "#199f4b", textColor: "#000000" }],
	["vim snippet", { backgroundColor: "#199f4b", textColor: "#000000" }],
	["visual basic .net", { backgroundColor: "#945db7", textColor: "#ffffff" }],
	["visual basic 6.0", { backgroundColor: "#2c6353", textColor: "#ffffff" }],
	["volt", { backgroundColor: "#1F1F1F", textColor: "#ffffff" }],
	["vue", { backgroundColor: "#41b883", textColor: "#000000" }],
	["vyper", { backgroundColor: "#9F4CF2", textColor: "#ffffff" }],
	["wdl", { backgroundColor: "#42f1f4", textColor: "#000000" }],
	["wgsl", { backgroundColor: "#1a5e9a", textColor: "#ffffff" }],
	["wavefront material", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["wavefront object", { backgroundColor: "#000000", textColor: "#ffffff" }],
	[
		"web ontology language",
		{ backgroundColor: "#5b70bd", textColor: "#ffffff" },
	],
	["webassembly", { backgroundColor: "#04133b", textColor: "#ffffff" }],
	[
		"webassembly interface type",
		{ backgroundColor: "#6250e7", textColor: "#ffffff" },
	],
	["webidl", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["webvtt", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["wget config", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["whiley", { backgroundColor: "#d5c397", textColor: "#000000" }],
	["wikitext", { backgroundColor: "#fc5757", textColor: "#ffffff" }],
	["win32 message file", { backgroundColor: "#000000", textColor: "#ffffff" }],
	[
		"windows registry entries",
		{ backgroundColor: "#52d5ff", textColor: "#000000" },
	],
	["witcher script", { backgroundColor: "#ff0000", textColor: "#ffffff" }],
	["wollok", { backgroundColor: "#a23738", textColor: "#ffffff" }],
	[
		"world of warcraft addon data",
		{ backgroundColor: "#f7e43f", textColor: "#000000" },
	],
	["wren", { backgroundColor: "#383838", textColor: "#ffffff" }],
	["x bitmap", { backgroundColor: "#000000", textColor: "#ffffff" }],
	[
		"x font directory index",
		{ backgroundColor: "#000000", textColor: "#ffffff" },
	],
	["x pixmap", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["x10", { backgroundColor: "#4B6BEF", textColor: "#ffffff" }],
	["xc", { backgroundColor: "#99DA07", textColor: "#000000" }],
	["xcompose", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["xml", { backgroundColor: "#0060ac", textColor: "#ffffff" }],
	["xml property list", { backgroundColor: "#0060ac", textColor: "#ffffff" }],
	["xpages", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["xproc", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["xquery", { backgroundColor: "#5232e7", textColor: "#ffffff" }],
	["xs", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["xslt", { backgroundColor: "#EB8CEB", textColor: "#000000" }],
	["xmake", { backgroundColor: "#22a079", textColor: "#ffffff" }],
	["xojo", { backgroundColor: "#81bd41", textColor: "#000000" }],
	["xonsh", { backgroundColor: "#285EEF", textColor: "#ffffff" }],
	["xtend", { backgroundColor: "#24255d", textColor: "#ffffff" }],
	["yaml", { backgroundColor: "#cb171e", textColor: "#ffffff" }],
	["yang", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["yara", { backgroundColor: "#220000", textColor: "#ffffff" }],
	["yasnippet", { backgroundColor: "#32AB90", textColor: "#000000" }],
	["yacc", { backgroundColor: "#4B6C4B", textColor: "#ffffff" }],
	["yul", { backgroundColor: "#794932", textColor: "#ffffff" }],
	["zap", { backgroundColor: "#0d665e", textColor: "#ffffff" }],
	["zil", { backgroundColor: "#dc75e5", textColor: "#000000" }],
	["zeek", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["zenscript", { backgroundColor: "#00BCD1", textColor: "#000000" }],
	["zephir", { backgroundColor: "#118f9e", textColor: "#ffffff" }],
	["zig", { backgroundColor: "#ec915c", textColor: "#000000" }],
	["zimpl", { backgroundColor: "#d67711", textColor: "#ffffff" }],
	["zmodel", { backgroundColor: "#ff7100", textColor: "#000000" }],
	["curl config", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["crontab", { backgroundColor: "#ead7ac", textColor: "#000000" }],
	["desktop", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["dircolors", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["ec", { backgroundColor: "#913960", textColor: "#ffffff" }],
	["edn", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["fish", { backgroundColor: "#4aae47", textColor: "#ffffff" }],
	["hoon", { backgroundColor: "#00b171", textColor: "#000000" }],
	["icalendar", { backgroundColor: "#ec564c", textColor: "#ffffff" }],
	["jq", { backgroundColor: "#c7254e", textColor: "#ffffff" }],
	["kvlang", { backgroundColor: "#1da6e0", textColor: "#000000" }],
	["mirc script", { backgroundColor: "#3d57c3", textColor: "#ffffff" }],
	["mcfunction", { backgroundColor: "#E22837", textColor: "#ffffff" }],
	["mdsvex", { backgroundColor: "#5f9ea0", textColor: "#ffffff" }],
	["mupad", { backgroundColor: "#244963", textColor: "#ffffff" }],
	["nanorc", { backgroundColor: "#2d004d", textColor: "#ffffff" }],
	["nesc", { backgroundColor: "#94B0C7", textColor: "#000000" }],
	["ooc", { backgroundColor: "#b0b77e", textColor: "#000000" }],
	["q", { backgroundColor: "#0040cd", textColor: "#ffffff" }],
	["restructuredtext", { backgroundColor: "#141414", textColor: "#ffffff" }],
	["robots.txt", { backgroundColor: "#000000", textColor: "#ffffff" }],
	["sed", { backgroundColor: "#64b970", textColor: "#000000" }],
	["templ", { backgroundColor: "#66D0DD", textColor: "#000000" }],
	["vcard", { backgroundColor: "#ee2647", textColor: "#ffffff" }],
	["wisp", { backgroundColor: "#7582D1", textColor: "#000000" }],
	["xbase", { backgroundColor: "#403a40", textColor: "#ffffff" }],
]);

export const skills = [
	"Java",
	"Kotlin",
	"Rust",
	"Kubernetes",
	"Linux",
	"Spring Boot",
	"gRPC",
	"Python",
	"Docker",
];

export const skillStyles: Record<string, { base: string; text: string }> = {
	Java: { base: "#f89920", text: "#fefce8" },
	Kotlin: { base: "#7f52ff", text: "#f5f3ff" },
	Rust: { base: "#dea584", text: "#fff7ed" },
	Kubernetes: { base: "#326ce5", text: "#e0f2fe" },
	Linux: { base: "#fcc624", text: "#fefce8" },
	"Spring Boot": { base: "#6db33f", text: "#ecfdf5" },
	gRPC: { base: "#5c9f55", text: "#ecfdf5" },
	Python: { base: "#3776ab", text: "#e0f2fe" },
	Docker: { base: "#0db7ed", text: "#e0f2fe" },
};
